# generated by datamodel-codegen:
#   filename:  game-radar-api.yaml
#   version:   0.83.0

from __future__ import annotations

from decimal import Decimal
from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, ConfigDict, Field, RootModel

from game_radar.schemas.base import DTO, CreateWatchlistRequestBase, UpdateItemRequestBase
from game_radar.schemas.types import Money


class CreateWatchlistRequest(CreateWatchlistRequestBase):
    """
    Создание списка наблюдения.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    name: str = Field(
        ...,
        description="Название списка, 1–100 символов.",
        max_length=100,
        min_length=1,
        pattern=".*\\S.*",
        title="Name",
    )


class RefreshResponse(DTO):
    """
    Данные GameRadar: RefreshResponse.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    watchlist_id: int = Field(
        ..., alias="watchlistId", description="Идентификатор списка.", title="Watchlist Id"
    )
    refreshed_games: int = Field(
        ...,
        alias="refreshedGames",
        description="Количество игр, обновлённых у провайдера, без попаданий в кеш.",
        title="Refreshed Games",
    )
    checked_items: int = Field(
        ...,
        alias="checkedItems",
        description="Количество проверенных позиций.",
        title="Checked Items",
    )
    matched_count: int = Field(
        ...,
        alias="matchedCount",
        description="Количество игр, достигших порога цены.",
        title="Matched Count",
    )
    notifications_created: int = Field(
        ...,
        alias="notificationsCreated",
        description="Количество новых записей уведомлений.",
        title="Notifications Created",
    )


class WatchlistResponse(DTO):
    """
    Данные GameRadar: WatchlistResponse.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    id: int = Field(..., description="Идентификатор объекта.", title="Id")
    name: str = Field(..., description="Название списка, 1–100 символов.", title="Name")
    created_at: AwareDatetime = Field(
        ..., alias="createdAt", description="Время создания в UTC.", title="Created At"
    )


class MoneyTarget1(RootModel[float]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: float = Field(
        ...,
        description="Неотрицательный порог USD: максимум 9999999999.99, не более 2 дробных цифр. Можно передать JSON-число или точную десятичную строку.",
        examples=["4.00", 4],
        ge=0.0,
        le=9999999999.99,
        multiple_of=0.01,
    )


class ProblemDetails(DTO):
    """
    Ошибка RFC 9457; секреты и введённые значения не возвращаются.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    type: str = Field(..., description="URI типа ошибки.")
    title: str = Field(..., description="Краткое название ошибки.")
    status: int = Field(..., description="HTTP-статус.", ge=400, le=599)
    detail: str = Field(..., description="Безопасное описание ошибки.")
    instance: str = Field(..., description="URI отдельного события ошибки (urn:uuid).")
    trace_id: UUID = Field(..., alias="traceId", description="Идентификатор трассировки.")
    code: str = Field(..., description="Стабильный код ошибки.")


class ValidationIssue(DTO):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    field: str = Field(..., description="Путь неверного поля.")
    type: str = Field(..., description="Тип нарушения.")
    message: str = Field(..., description="Описание нарушения без введённого значения.")


class ValidationProblemDetails(ProblemDetails):
    """
    Ошибка валидации запроса.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    errors: list[ValidationIssue] = Field(..., description="Нарушения ограничений.")


class HealthResponse(DTO):
    """
    Готовность базы данных и выбранный источник цен.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    status: Literal["ok"] = Field(..., description="Сервис готов.")
    database: Literal["ready"] = Field(..., description="БД доступна, схема установлена.")
    price_source: Literal["mock", "cheapshark"] = Field(
        ..., alias="priceSource", description="Источник цен."
    )
    mock_prices_are_fictional: bool = Field(
        ..., alias="mockPricesAreFictional", description="Цены mock вымышленные."
    )


class AddItemRequest(DTO):
    """
    Добавление игры и порога цены в список.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    game_id: str = Field(
        ...,
        alias="gameId",
        description="Идентификатор CheapShark: от 1 до 32 цифр, это не Steam App ID.",
        pattern="^[0-9]{1,32}$",
        title="Gameid",
    )
    target_price: Money = Field(
        ...,
        alias="targetPrice",
        description="Порог цены USD: неотрицательное число, до 10 целых и 2 дробных цифр.",
    )
    steam_only: bool = Field(
        True,
        alias="steamOnly",
        description="Учитывать только предложения магазина Steam.",
        title="Steamonly",
    )


class GameCard(DTO):
    """
    Данные GameRadar: GameCard.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    id: str = Field(..., description="Идентификатор объекта.", title="Id")
    title: str = Field(..., description="Название игры.", title="Title")
    steam_app_id: str | None = Field(
        ...,
        alias="steamAppId",
        description="Идентификатор Steam App; null, если привязка отсутствует.",
        title="Steam App Id",
    )
    thumbnail_url: str | None = Field(
        ...,
        alias="thumbnailUrl",
        description="URL изображения игры; null, если изображения нет.",
        title="Thumbnail Url",
    )
    cheapest_price: Decimal | None = Field(
        ...,
        alias="cheapestPrice",
        description="Минимальная известная цена; null, если предложений нет.",
    )
    currency: Literal["USD"] = Field("USD", description="Валюта цены: USD.", title="Currency")
    source: Literal["mock", "cheapshark"] = Field(
        ..., description="Источник данных: mock или cheapshark.", title="Source"
    )


class ItemResponse(DTO):
    """
    Данные GameRadar: ItemResponse.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    id: int = Field(..., description="Идентификатор объекта.", title="Id")
    game_id: str = Field(
        ...,
        alias="gameId",
        description="Идентификатор CheapShark: от 1 до 32 цифр, это не Steam App ID.",
        title="Game Id",
    )
    target_price: Decimal = Field(
        ...,
        alias="targetPrice",
        description="Порог цены USD: неотрицательное число, до 10 целых и 2 дробных цифр.",
    )
    steam_only: bool = Field(
        ...,
        alias="steamOnly",
        description="Учитывать только предложения магазина Steam.",
        title="Steam Only",
    )
    created_at: AwareDatetime = Field(
        ..., alias="createdAt", description="Время создания в UTC.", title="Created At"
    )
    game: GameCard = Field(..., description="Карточка игры.")
    current_price: Decimal | None = Field(
        ...,
        alias="currentPrice",
        description="Лучшая цена с учётом steamOnly; null при отсутствии предложения.",
    )
    threshold_met: bool = Field(
        ...,
        alias="thresholdMet",
        description="Цена доступна и не превышает targetPrice.",
        title="Threshold Met",
    )


class NotificationResponse(DTO):
    """
    Данные GameRadar: NotificationResponse.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    id: int = Field(..., description="Идентификатор объекта.", title="Id")
    watchlist_id: int = Field(
        ..., alias="watchlistId", description="Идентификатор списка.", title="Watchlist Id"
    )
    item_id: int | None = Field(
        ...,
        alias="itemId",
        description="Идентификатор позиции; null после её удаления.",
        title="Item Id",
    )
    game_id: str = Field(
        ...,
        alias="gameId",
        description="Идентификатор CheapShark: от 1 до 32 цифр, это не Steam App ID.",
        title="Game Id",
    )
    game_title: str = Field(
        ...,
        alias="gameTitle",
        description="Название игры на момент уведомления.",
        title="Game Title",
    )
    target_price: Decimal = Field(
        ...,
        alias="targetPrice",
        description="Порог цены USD: неотрицательное число, до 10 целых и 2 дробных цифр.",
    )
    observed_price: Decimal = Field(
        ..., alias="observedPrice", description="Цена, вызвавшая уведомление, в USD."
    )
    created_at: AwareDatetime = Field(
        ..., alias="createdAt", description="Время создания в UTC.", title="Created At"
    )


class OfferResponse(DTO):
    """
    Данные GameRadar: OfferResponse.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    deal_id: str = Field(
        ..., alias="dealId", description="Идентификатор предложения в источнике.", title="Deal Id"
    )
    store_id: str = Field(
        ..., alias="storeId", description="Идентификатор магазина.", title="Store Id"
    )
    store_name: str = Field(
        ..., alias="storeName", description="Название магазина.", title="Store Name"
    )
    price: Decimal = Field(..., description="Текущая цена предложения в USD.")
    retail_price: Decimal = Field(..., alias="retailPrice", description="Обычная цена в USD.")
    savings: Decimal = Field(..., description="Процент скидки.")
    deal_url: str | None = Field(
        None,
        alias="dealUrl",
        description="URL покупки; null, если URL отсутствует.",
        title="Deal Url",
    )


class SnapshotResponse(DTO):
    """
    Данные GameRadar: SnapshotResponse.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    id: int = Field(..., description="Идентификатор объекта.", title="Id")
    game_id: str = Field(
        ...,
        alias="gameId",
        description="Идентификатор CheapShark: от 1 до 32 цифр, это не Steam App ID.",
        title="Game Id",
    )
    store_id: str = Field(
        ..., alias="storeId", description="Идентификатор магазина.", title="Store Id"
    )
    deal_id: str = Field(
        ..., alias="dealId", description="Идентификатор предложения в источнике.", title="Deal Id"
    )
    price: Decimal = Field(..., description="Текущая цена предложения в USD.")
    observed_at: AwareDatetime = Field(
        ..., alias="observedAt", description="Время наблюдения цены в UTC.", title="Observed At"
    )
    source: Literal["mock", "cheapshark"] = Field(
        ..., description="Источник данных: mock или cheapshark.", title="Source"
    )


class SummaryResponse(DTO):
    """
    Данные GameRadar: SummaryResponse.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    watchlist_id: int = Field(
        ..., alias="watchlistId", description="Идентификатор списка.", title="Watchlist Id"
    )
    total_items: int = Field(
        ..., alias="totalItems", description="Количество игр в списке.", title="Total Items"
    )
    priced_items: int = Field(
        ...,
        alias="pricedItems",
        description="Количество игр с доступной ценой.",
        title="Priced Items",
    )
    matched_count: int = Field(
        ...,
        alias="matchedCount",
        description="Количество игр, достигших порога цены.",
        title="Matched Count",
    )
    current_total: Decimal = Field(
        ..., alias="currentTotal", description="Сумма доступных цен игр списка в USD."
    )
    currency: Literal["USD"] = Field(..., description="Валюта цены: USD.", title="Currency")
    source: Literal["mock", "cheapshark", "mixed"] = Field(
        ..., description="Источник цен: mock, cheapshark или mixed.", title="Source"
    )


class UpdateItemRequest(UpdateItemRequestBase):
    """
    Изменение хотя бы одного поля; null запрещён.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    target_price: Money | None = Field(
        None,
        alias="targetPrice",
        description="Порог цены USD: неотрицательное число, до 10 целых и 2 дробных цифр.",
    )
    steam_only: bool | None = Field(
        None, alias="steamOnly", description="Учитывать только предложения магазина Steam."
    )


class WatchlistDetails(DTO):
    """
    Данные GameRadar: WatchlistDetails.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    id: int = Field(..., description="Идентификатор объекта.", title="Id")
    name: str = Field(..., description="Название списка, 1–100 символов.", title="Name")
    created_at: AwareDatetime = Field(
        ..., alias="createdAt", description="Время создания в UTC.", title="Created At"
    )
    items: list[ItemResponse] = Field(..., description="Игры списка наблюдения.", title="Items")


class GameDetails(DTO):
    """
    Данные GameRadar: GameDetails.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        frozen=True,
    )
    id: str = Field(..., description="Идентификатор объекта.", title="Id")
    title: str = Field(..., description="Название игры.", title="Title")
    steam_app_id: str | None = Field(
        ...,
        alias="steamAppId",
        description="Идентификатор Steam App; null, если привязка отсутствует.",
        title="Steam App Id",
    )
    thumbnail_url: str | None = Field(
        ...,
        alias="thumbnailUrl",
        description="URL изображения игры; null, если изображения нет.",
        title="Thumbnail Url",
    )
    cheapest_price: Decimal | None = Field(
        ...,
        alias="cheapestPrice",
        description="Минимальная известная цена; null, если предложений нет.",
    )
    currency: Literal["USD"] = Field("USD", description="Валюта цены: USD.", title="Currency")
    source: Literal["mock", "cheapshark"] = Field(
        ..., description="Источник данных: mock или cheapshark.", title="Source"
    )
    last_refreshed_at: AwareDatetime | None = Field(
        ...,
        alias="lastRefreshedAt",
        description="Время последнего обновления в UTC; null до первого наблюдения.",
        title="Last Refreshed At",
    )
    offers: list[OfferResponse] = Field(
        ..., description="Текущие предложения магазинов.", title="Offers"
    )
    best_price: Decimal | None = Field(
        ..., alias="bestPrice", description="Лучшая текущая цена или null."
    )
