"""Generate Core tables with sqlacodegen without putting credentials in command arguments.

Default mode reflects the already migrated DATABASE_URL from the project environment.
`--from-migration` uses the initial migration's SQLAlchemy schema objects offline;
it does not inspect a live PostgreSQL database or lose PostgreSQL timezone types.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from collections.abc import Sequence
from importlib.metadata import version
from pathlib import Path

from sqlacodegen.generators import TablesGenerator
from sqlalchemy import Index, MetaData, Table, create_engine, create_mock_engine

ROOT = Path(__file__).resolve().parents[1]
BASELINE = ROOT / "migrations/versions/f56047282f20_initial_game_monitoring_schema.py"
sys.path.insert(0, str(ROOT))


class BaselineSchema:
    """Record the initial migration's table/index operations as exact Core metadata."""

    def __init__(self):
        self.metadata = MetaData()

    @staticmethod
    def f(name: str) -> str:
        return name

    def create_table(self, name: str, *elements, **kwargs) -> Table:
        return Table(name, self.metadata, *elements, **kwargs)

    def create_index(
        self, name: str, table_name: str, columns: Sequence[str], *, unique: bool = False
    ) -> None:
        table = self.metadata.tables[table_name]
        Index(name, *(table.c[column] for column in columns), unique=unique)


def baseline_metadata() -> MetaData:
    specification = importlib.util.spec_from_file_location("gameradar_baseline", BASELINE)
    if specification is None or specification.loader is None:
        raise RuntimeError("Cannot load baseline migration")
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    recorder = BaselineSchema()
    module.op = recorder
    module.upgrade()
    return recorder.metadata


def generate(output: Path, *, from_migration: bool) -> None:
    if from_migration:
        metadata = baseline_metadata()
        bind = create_mock_engine("postgresql://", lambda *args, **kwargs: None)
        generated = TablesGenerator(metadata, bind, options=[]).generate()
        origin = "schema metadata captured from Alembic baseline f56047282f20 (offline)"
    else:
        # Read trusted configuration in-process; never put a database URL in argv or logs.
        from app.config import get_settings

        engine = create_engine(get_settings().database_url)
        try:
            with engine.connect() as connection:
                metadata = MetaData()
                metadata.reflect(
                    bind=connection, only=lambda table_name, _: table_name != "alembic_version"
                )
                generated = TablesGenerator(metadata, connection, options=[]).generate()
        finally:
            engine.dispose()
        origin = "reflection of the configured migrated database; alembic_version excluded"
    header = (
        f'"""Generated by sqlacodegen {version("sqlacodegen")} using TablesGenerator.\n\n'
        f"Source: {origin}.\n"
        "Regenerate with scripts/generate_models.py; no ORM classes are used.\n"
        '"""\n\n'
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".tmp")
    temporary.write_text(header + generated, encoding="utf-8", newline="\n")
    temporary.replace(output)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "app/models/tables.py")
    parser.add_argument(
        "--from-migration",
        action="store_true",
        help="Generate from baseline schema objects without a database connection",
    )
    args = parser.parse_args()
    try:
        generate(args.output.resolve(), from_migration=args.from_migration)
    except Exception as exc:
        # Provider/driver exceptions can contain credentials or a complete DSN.
        raise SystemExit(
            f"Model generation failed ({type(exc).__name__}); "
            "check configuration and dev dependencies"
        ) from None
    print("Generated SQLAlchemy Core tables; database URL and credentials were not printed.")


if __name__ == "__main__":
    main()
