"""Generated by sqlacodegen 3.2.0 using TablesGenerator.

Source: schema metadata captured from Alembic baseline f56047282f20 (offline).
Regenerate with scripts/generate_models.py; no ORM classes are used.
"""

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    UniqueConstraint,
)

metadata = MetaData()


t_games = Table(
    "games",
    metadata,
    Column("id", String(32), primary_key=True),
    Column("title", String(300), nullable=False),
    Column("steam_app_id", String(32)),
    Column("thumbnail_url", String(2048)),
    Column("source", String(20), nullable=False),
    Column("cheapest_price", Numeric(12, 2)),
    Column("last_refreshed_at", DateTime(True)),
)

t_watchlists = Table(
    "watchlists",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(100), nullable=False),
    Column("created_at", DateTime(True), nullable=False),
)

t_offers = Table(
    "offers",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("game_id", ForeignKey("games.id", ondelete="CASCADE"), nullable=False),
    Column("deal_id", String(512), nullable=False),
    Column("store_id", String(32), nullable=False),
    Column("price", Numeric(12, 2), nullable=False),
    Column("retail_price", Numeric(12, 2), nullable=False),
    Column("savings", Numeric(12, 6), nullable=False),
    UniqueConstraint("game_id", "deal_id"),
    Index("ix_offers_game_id", "game_id"),
)

t_price_snapshots = Table(
    "price_snapshots",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("game_id", ForeignKey("games.id", ondelete="CASCADE"), nullable=False),
    Column("store_id", String(32), nullable=False),
    Column("deal_id", String(512), nullable=False),
    Column("price", Numeric(12, 2), nullable=False),
    Column("source", String(20), nullable=False),
    Column("observed_at", DateTime(True), nullable=False),
    Index("ix_price_snapshots_game_observed", "game_id", "observed_at"),
)

t_watchlist_items = Table(
    "watchlist_items",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("watchlist_id", ForeignKey("watchlists.id", ondelete="CASCADE"), nullable=False),
    Column("game_id", ForeignKey("games.id"), nullable=False),
    Column("target_price", Numeric(12, 2), nullable=False),
    Column("steam_only", Boolean, nullable=False),
    Column("alert_active", Boolean, nullable=False),
    Column("created_at", DateTime(True), nullable=False),
    UniqueConstraint("watchlist_id", "game_id"),
    Index("ix_watchlist_items_game_id", "game_id"),
    Index("ix_watchlist_items_watchlist_id", "watchlist_id"),
)

t_notifications = Table(
    "notifications",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("watchlist_id", ForeignKey("watchlists.id", ondelete="CASCADE"), nullable=False),
    Column("item_id", ForeignKey("watchlist_items.id", ondelete="SET NULL")),
    Column("game_id", ForeignKey("games.id"), nullable=False),
    Column("game_title", String(300), nullable=False),
    Column("target_price", Numeric(12, 2), nullable=False),
    Column("observed_price", Numeric(12, 2), nullable=False),
    Column("created_at", DateTime(True), nullable=False),
    Index("ix_notifications_watchlist_created", "watchlist_id", "created_at"),
)
